"""Add thumbnail to lessons

Revision ID: 133a2b351f4b
Revises: 28c8f428443e
Create Date: 2025-12-14 12:17:09.321088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133a2b351f4b'
down_revision: Union[str, Sequence[str], None] = '28c8f428443e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'thumbnail')
    # ### end Alembic commands ###
