"""Add language column to news_items

Revision ID: 28c8f428443e
Revises: a21dff1f8740
Create Date: 2025-12-12 00:53:25.608515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c8f428443e'
down_revision: Union[str, Sequence[str], None] = 'a21dff1f8740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('language', sa.String(length=5), nullable=True))
    op.create_index(op.f('ix_news_items_language'), 'news_items', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_language'), table_name='news_items')
    op.drop_column('news_items', 'language')
    # ### end Alembic commands ###
