"""Add quiz_attempts and Certificate model

Revision ID: c9718af8c1a9
Revises: e50f03c697d9
Create Date: 2025-12-11 09:26:49.313762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9718af8c1a9'
down_revision: Union[str, Sequence[str], None] = 'e50f03c697d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('quiz_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'quiz_attempts')
    # ### end Alembic commands ###
